defmodule Euler do
  @moduledoc """
  Documentation for Euler.
  """

  @doc """
  Hello world.

  ## Examples

      iex> Euler.hello
      :world

  """
  def hello do
    :world
  end

  # Project Euler Problem 1
  # If we list all the natural numbers below 10 that are 
  # multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
  # Find the sum of all the multiples of 3 or 5 below 1000.
  # Answer: 233168

  def p1(totalSum, start, limit) do
    addDivBy3Or5(totalSum, start, limit)
  end

  defp addDivBy3Or5(totalSum, iter, limit) do
    if iter < limit do
      if rem(iter, 3) == 0 or rem(iter, 5) == 0 do
        totalSum = totalSum + iter
      end
      addDivBy3Or5(totalSum, iter+1, limit)
    else
      totalSum
    end
  end

  # Project Euler Problem 2
  # Each new term in the Fibonacci sequence is generated by adding 
  # the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  # By considering the terms in the Fibonacci sequence whose values 
  # do not exceed four million, find the sum of the even-valued terms.
  # Answer: 4613732
  
  def p2 do

  end

end
